import {
  SiApachespark,
  SiApachekafka,
  SiApacheairflow,
  SiApachehive,
  SiApachehadoop,
  SiSnowflake,
  SiDatabricks,
  SiPython,
  SiJenkins,
  SiGit,
  SiGithub,
  SiLinux,
  SiOpenjdk,
  SiPostgresql,
  SiDocker,
  SiMysql,
  SiGnubash,
  SiKubernetes,
  SiScala,
  SiGooglecloud,
  SiTerraform,
  SiPandas,
  SiNumpy,
  SiAnaconda,
  SiJira,
  SiConfluence,
  SiSplunk,
  SiGrafana,
  SiRedis,
  SiMongodb,
  SiAngular,
  SiTypescript,
  SiJavascript,
  SiReact,
  SiHtml5,
  SiCss,
  SiNodedotjs,
  SiPlotly,
  SiDbt,
  SiApachecassandra,
  SiPresto,
} from "react-icons/si";
import { FaAws } from "react-icons/fa6";
import { VscAzure, VscAzureDevops } from "react-icons/vsc";
import {
  Database,
  Workflow,
  GitBranch,
  Users,
  Server,
  Cloud,
  HardDrive,
  BarChart3,
  Sparkles,
  Mail,
  Settings,
} from "lucide-react";

export type IconComp = React.ComponentType<{ className?: string; style?: React.CSSProperties }>;

export const SKILL_ICONS: Record<string, IconComp> = {
  spark: SiApachespark,
  pyspark: SiApachespark,
  kafka: SiApachekafka,
  airflow: SiApacheairflow,
  hive: SiApachehive,
  hadoop: SiApachehadoop,
  snowflake: SiSnowflake,
  databricks: SiDatabricks,
  python: SiPython,
  jenkins: SiJenkins,
  git: SiGit,
  github: SiGithub,
  linux: SiLinux,
  java: SiOpenjdk,
  postgresql: SiPostgresql,
  docker: SiDocker,
  mysql: SiMysql,
  bash: SiGnubash,
  kubernetes: SiKubernetes,
  scala: SiScala,
  aws: FaAws,
  gcp: SiGooglecloud,
  azure: VscAzure,
  adf: VscAzure,
  "azure-devops": VscAzureDevops,
  terraform: SiTerraform,
  pandas: SiPandas,
  numpy: SiNumpy,
  anaconda: SiAnaconda,
  jira: SiJira,
  confluence: SiConfluence,
  splunk: SiSplunk,
  grafana: SiGrafana,
  redis: SiRedis,
  mongodb: SiMongodb,
  angular: SiAngular,
  typescript: SiTypescript,
  javascript: SiJavascript,
  react: SiReact,
  html: SiHtml5,
  css: SiCss,
  nodejs: SiNodedotjs,
  tableau: BarChart3,
  plotly: SiPlotly,
  dbt: SiDbt,
  delta: HardDrive,
  cassandra: SiApachecassandra,
  presto: SiPresto,
  "control-m": Settings,
  sftp: Server,
  email: Mail,
  database: Database,
  workflow: Workflow,
  gitbranch: GitBranch,
  users: Users,
  server: Server,
  cloud: Cloud,
  harddrive: HardDrive,
  chart: BarChart3,
  sparkles: Sparkles,
};

// Native brand colors for the icons (when available).
export const SKILL_COLORS: Record<string, string> = {
  spark: "#E25A1C",
  pyspark: "#E25A1C",
  kafka: "#231F20",
  airflow: "#017CEE",
  hive: "#FDEE21",
  hadoop: "#66CCFF",
  snowflake: "#29B5E8",
  databricks: "#FF3621",
  python: "#3776AB",
  jenkins: "#D24939",
  git: "#F05032",
  github: "#FFFFFF",
  linux: "#FCC624",
  java: "#007396",
  postgresql: "#4169E1",
  docker: "#2496ED",
  mysql: "#4479A1",
  bash: "#4EAA25",
  kubernetes: "#326CE5",
  scala: "#DC322F",
  aws: "#FF9900",
  gcp: "#4285F4",
  azure: "#0078D4",
  adf: "#0078D4",
  "azure-devops": "#0078D4",
  terraform: "#7B42BC",
  pandas: "#150458",
  numpy: "#013243",
  anaconda: "#44A833",
  jira: "#0052CC",
  confluence: "#172B4D",
  splunk: "#000000",
  grafana: "#F46800",
  redis: "#DC382D",
  mongodb: "#47A248",
  angular: "#DD0031",
  typescript: "#3178C6",
  javascript: "#F7DF1E",
  react: "#61DAFB",
  html: "#E34F26",
  css: "#1572B6",
  nodejs: "#5FA04E",
  tableau: "#E97627",
  plotly: "#3F4F75",
  dbt: "#FF694A",
  delta: "#00ADD4",
  cassandra: "#1287B1",
  presto: "#5890FF",
  "control-m": "#9CA3AF",
  sftp: "#9CA3AF",
  email: "#9CA3AF",
};

export const ICON_OPTIONS = Object.keys(SKILL_ICONS);

export function getSkillIcon(key: string): IconComp {
  return SKILL_ICONS[key] ?? Sparkles;
}

export function getSkillColor(key: string): string | undefined {
  return SKILL_COLORS[key];
}

// Pretty labels for tech-stack chips
const LABELS: Record<string, string> = {
  pyspark: "PySpark",
  adf: "Azure Data Factory",
  "azure-devops": "Azure DevOps",
  aws: "AWS",
  gcp: "GCP",
  gnubash: "Bash",
  nodejs: "Node.js",
  html: "HTML5",
  css: "CSS3",
  "control-m": "Control-M",
  sftp: "SFTP",
  dbt: "dbt",
};

export function getSkillLabel(key: string): string {
  if (LABELS[key]) return LABELS[key];
  return key.charAt(0).toUpperCase() + key.slice(1);
}
